on: push
name: on push to gosuapi    
jobs:
  gitHubActionForPytest:
    name: Github Action for pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: github action for gosuapi
      uses: cclauss/Github-Action-for-pytest@master
      with:
        args: pip install -r requirements.txt && python setup.py develop && pytest
